export default  {
    MIN_USER_DISPLAY_NAME_LENGTH: 3,
    MIN_PASSWORD_LENGTH: 3,
    PROFILE_STATUS_ACTIVE: 'PROFILE_STATUS_ACTIVE',
    PROFILE_STATUS_CONFIRMATION_PENDING: 'PROFILE_STATUS_CONFIRMATION_PENDING',
    PROFILE_STATUS_REGISTRATION_PENDING: 'PROFILE_STATUS_REGISTRATION_PENDING',
    PROFILE_STATUS_DISABLED: 'PROFILE_STATUS_DISABLED',
    ERROR_SUCCESS: 'success',
    ERROR_AUTH_INVALID_CREDENTIALS: 'ERROR_AUTH_INVALID_CREDENTIALS',
    ERROR_REGISTRATION_EMAIL_SENDING_FAILURE: 'ERROR_REGISTRATION_EMAIL_SENDING_FAILURE',
    ERROR_REGISTRATION_USER_ALREADY_EXISTS: 'ERROR_REGISTRATION_ACTIVE_USER_ALREADY_EXISTS',
}