export default  {
    MIN_USER_DISPLAY_NAME_LENGTH: 3,
    MIN_PASSWORD_LENGTH: 3,
    USER_STATUS_ACTIVE: 'active',
    USER_STATUS_CONFIRMATION_PENDING: 'confirmation_pending',
    USER_STATUS_REGISTRATION_PENDING: 'registration_pending',
    USER_STATUS_DISABLED: 'disabled',
    ERROR_SUCCESS: 'success',
    ERROR_API_CALL_FAILED: 'ERROR_API_CALL_FAILED',
    ERROR_AUTH_INVALID_CREDENTIALS: 'ERROR_AUTH_INVALID_CREDENTIALS',
    ERROR_REGISTRATION_DATABASE_FAILURE: 'ERROR_REGISTRATION_DATABASE_FAILURE',
    ERROR_REGISTRATION_EMAIL_SENDING_FAILURE: 'ERROR_REGISTRATION_EMAIL_SENDING_FAILURE',
    ERROR_REGISTRATION_USER_ALREADY_EXISTS: 'ERROR_REGISTRATION_ACTIVE_USER_ALREADY_EXISTS',
    ERROR_REGISTRATION_INVALID_CODE: 'ERROR_REGISTRATION_INVALID_CODE'
};